{
 "title": "Smart green House",
 "time": { "from": "2025-02-23T04:45:39.000Z", "to": "2025-02-23T04:48:10.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Light",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"environment_data\")\n  |> filter(fn: (r) => r._field == \"light_level\")\n"
    }
   ]
  },
  {
   "title": "soil moisture Reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"environment_data\")\n  |> filter(fn: (r) => r._field == \"soil_moisture\")\n"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"environment_data\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"esp32\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r._measurement == \"environment_data\")\n  |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  }
 ]
}